<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Коментар',
    'Entity' => 'Модель',
    'Entity ID' => 'ID модели',
    'Parent ID' => 'Батько',
    'Status' => 'Статус',
    'Level' => 'Рівень',
    'Created by' => 'Створено',
    'Updated by' => 'Оновлено',
    'Related to' => 'Відноситься до',
    'Url' => 'Url',
    'Created date' => 'Дата створення',
    'Updated date' => 'Дата оновлення',
    'View' => 'Перегляд',
    'Update' => 'Обновити',
    'Delete' => 'Видалити',
    'Reply' => 'Відповісти',
    'Comments ({0})' => 'Коментарі ({0})',
    'Comment cannot be blank.' => 'Коментар не може бути порожнім.',
    'Comment has not been deleted. Please try again!' => 'Не вдалося видалити коментар. Спробуйте будь ласка ще раз!',
    'Add a comment...' => 'Додати коментар...',
    'Comment' => 'Опублікувати коментар',
    'Oops, something went wrong. Please try again later.' => 'Не вдалося додати коментар. Спробуйте будь ласка ще раз.',
    'The requested page does not exist.' => 'Помилка 404 - сторінка не знайдена!',
    'Comment has been deleted.' => 'Коментар був видалений.',
    'Comment has been saved.' => 'Коментар був збережений.',
    'Click here to cancel reply.' => 'Натисніть тут, щоб скасувати відповідь.',
    'Comments Management' => 'Управління Коментарями',
    'Select Status' => 'Оберіть Статус',
    'Select Author' => 'Оберіть Автора',
    'Update Comment: {0}' => 'Обновити коментар: {0}',
    'Active' => 'Активно',
    'Deleted' => 'Видалено',
    'Go Back' => 'Вернуться',
];
